FROM python:3.6

WORKDIR /app

ADD requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

ADD . /app

RUN pytest --cov=src --cov-report=html:reports/html_dir --cov-report=xml:reports/coverage.xml
CMD ["echo", "hello world"]